import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Jose Cebreros | CS Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Jose Roberto Cebreros</h1>
      </header>
      <main>
        <div className="SelfPortrait">
          <Image
            src="/me.jpeg"
            alt="Portrait of myself."
            width={200}
            height={300}
          />
        </div>
        <p>Hello, Welcome!</p>
        <p>My name is Jose Roberto Cebreros, im 21 years old, im currently in my senior year at University pursuing a Bachelor's in Computer Science at CETYS Universidad in Tijuana, Mexico</p>
        <p>At this time, im having an Internship experience as a Software QA Engineer at Dexcom, Inc. a company that develops, manufactures, produces, and distributes continuous glucose monitoring systems for diabetes management.</p>
        <p>I encourage you to follow me on my social, and learn more About me:</p>
      </main>
      <footer>
        <p>Latest Rev. September 2024</p>
      </footer>
       
    </>
  );
}
