// index.tsx
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import { BsFillPersonLinesFill } from "react-icons/bs";
import { PiBracketsAngle } from "react-icons/pi";
import { MdPermContactCalendar } from "react-icons/md";
import { IoSchoolSharp } from "react-icons/io5";
import SocialMedia from "./SocialMedia";
import DarkModeToggle from "./DarkModeToggle";
import { useEffect, useState } from 'react';

const Home = () => {
  // Estado para controlar la visibilidad y aplicar la clase de fade-in
  const [isVisible, setIsVisible] = useState(false);

  // useEffect se ejecuta al montar el componente, activando la animación
  useEffect(() => {
    setIsVisible(true); // Activa el fade-in cuando el componente se carga
  }, []);

  return (
    <>
      <Head>
        <title>Jose R Cebreros | CS Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/new-favicon.ico" />
      </Head>
      <div className={`UIMainScreen ${isVisible ? 'fade-in' : ''}`}>
        <header className="MainHeader">
          <span>Jose Cebreros</span>
          <DarkModeToggle />
        </header>
        <main>
          {/* Corrección de las comillas para aplicar la clase de manera correcta */}
          <div className="mainScreen">
            <div className="SelfPortrait">
              <img
                src="/me.png"
                alt="Portrait of myself."
                className="responsive-image"
              />
            </div>
            <div className="IntroText">
              <span>Hello, Welcome</span>
              <p>I'm <b>Jose Roberto Cebreros</b>, 21 years old, currently in my senior year pursuing a Bachelor's in Computer Science at CETYS Universidad.</p>
              <br />
              <p>I encourage you to follow me on my social, and learn more About me:</p>
              <div className="Buttons">
                <button className="ButtonsContent">About Me <BsFillPersonLinesFill /></button>
                <button className="ButtonsContent">Work Experience & Education <IoSchoolSharp /></button>
                <button className="ButtonsContent">Projects <PiBracketsAngle /></button>
                <button className="ButtonsContent">Contact Me <MdPermContactCalendar /></button>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
